### ISSUE TITLE
App not updating

### ISSUE THREAD

**Issue by Relent97** [laudio/pyodbc#49] opened 2020-06-07 23:18 UTC
Hi @laudio

I love your docker image however, the app does not pull up to date data from the database  within the docker container, hence the app does not update itself.

What can I do to solve this please

**Comment by kabirbaidhya** [comment] 2020-06-08 06:17
@Relent97 Could you be more specific to the issue? Not sure what the issue is. 

Let us know what the issue is, when do you get it and how you're using it and probably we can help you out. Thanks!

**Comment by Relent97** [comment] 2020-06-08 10:57
Hi @kabirbaidhya , Thanks for your response. 

So the issue can be best be explained in an example. I built my docker image yesterday using the base Dockerfile in your repository with some minor changes.The container would build successfuly  and run pulling the data from from a specified db in my Azure environment.
The problem is that, if i check the app today, the app does not pull any data for today from the DB. It's as if it only pulls data when the image is built and does not update itself hence losing it's dynamism.

Below is the syntax
FROM python:3.7-slim AS base

COPY requirements.txt .

# Setup dependencies for pyodbc
RUN \
  export ACCEPT_EULA='Y' && \
  export MYSQL_CONNECTOR='mysql-connector-odbc-8.0.18-linux-glibc2.12-x86-64bit' && \
  export MYSQL_CONNECTOR_CHECKSUM='f2684bb246db22f2c9c440c4d905dde9' && \
  apt-get update && \
  apt-get install -y curl build-essential unixodbc-dev g++ apt-transport-https && \
  gpg --keyserver hkp://keys.gnupg.net --recv-keys 5072E1F5 && \
  #
  # Install pyodbc db drivers for MSSQL, PG and MySQL
  curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
  curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
  curl -L -o ${MYSQL_CONNECTOR}.tar.gz https://dev.mysql.com/get/Downloads/Connector-ODBC/8.0/${MYSQL_CONNECTOR}.tar.gz && \
  curl -L -o ${MYSQL_CONNECTOR}.tar.gz.asc https://downloads.mysql.com/archives/gpg/\?file\=${MYSQL_CONNECTOR}.tar.gz\&p\=10 && \
  gpg --verify ${MYSQL_CONNECTOR}.tar.gz.asc && \
  echo "${MYSQL_CONNECTOR_CHECKSUM} ${MYSQL_CONNECTOR}.tar.gz" | md5sum -c - && \
  apt-get update && \
  gunzip ${MYSQL_CONNECTOR}.tar.gz && tar xvf ${MYSQL_CONNECTOR}.tar && \
  cp ${MYSQL_CONNECTOR}/bin/* /usr/local/bin && cp ${MYSQL_CONNECTOR}/lib/* /usr/local/lib && \
  myodbc-installer -a -d -n "MySQL ODBC 8.0 Driver" -t "Driver=/usr/local/lib/libmyodbc8w.so" && \
  myodbc-installer -a -d -n "MySQL ODBC 8.0" -t "Driver=/usr/local/lib/libmyodbc8a.so" && \
  apt-get install -y msodbcsql17 odbc-postgresql && \
  #
  # Update odbcinst.ini to make sure full path to driver is listed
  sed 's/Driver=psql/Driver=\/usr\/lib\/x86_64-linux-gnu\/odbc\/psql/' /etc/odbcinst.ini > /tmp/temp.ini && \
  mv -f /tmp/temp.ini /etc/odbcinst.ini && \
  # Install dependencies
  pip install --upgrade pip && \
  pip install -r requirements.txt && rm requirements.txt && \

  # Cleanup build dependencies
  rm -rf ${MYSQL_CONNECTOR}* && \
  apt-get remove -y curl apt-transport-https debconf-utils g++ gcc rsync unixodbc-dev build-essential gnupg2 && \
  apt-get autoremove -y && apt-get autoclean -y

RUN mkdir /app
WORKDIR /app


ADD requirements.txt /app/

RUN pip install -r requirements.txt

ADD . /app/

ENTRYPOINT ["python3", "app.py"]

**Comment by kabirbaidhya** [comment] 2020-06-10 11:33
@Relent97 I'm still not clear about your issue. Also, I don't think this issue is related to the `laudio/pyodbc` image since it seems you're not using it and are building your own using the dockerfile code as a reference. So, I'm closing this issue.

Anyway, I can suggest following: 
- You're creating your own image from scratch with `python:3.7-slim` as base - is this required? You could have used this image as a base or have extended from it in case you need custom chnages.
- If you're looking for building your own image then perhaps you should go through the issue thread https://github.com/mkleehammer/pyodbc/issues/276 and see if any other issues here answers your question https://github.com/mkleehammer/pyodbc/issues.

**Closed as completed by kabirbaidhya** 2020-06-10 11:33 UTC
Labels: under discussion

**Comment by Relent97** [comment] 2020-06-15 13:21
Thank you for the pointers @kabirbaidhya
